import { useNavigate } from 'react-router-dom';
import { useSettingsStore } from '@/stores/settingsStore';
import { useAuth } from '@/hooks/useAuth';
import { updateUserPreferences } from '@/api/users';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useUIStore } from '@/stores/uiStore';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { Switch } from '@/components/ui/Switch';
import { Select } from '@/components/ui/Select';
import { User, Shield, BarChart3, ChevronRight } from 'lucide-react';
import { AutoBetConfig } from '@/components/betting/AutoBetConfig';
const sections=[['account','Account'],['betting','Betting'],['notifications','Notifications'],['appearance','Appearance'],['security','Security'],['telegram','Telegram'],['risk','Risk'],['about','About']];
export function SettingsScreen(){ const navigate=useNavigate(); const {user,isOperator,isAdmin,logout}=useAuth(); const settings=useSettingsStore(); const update=useSettingsStore(s=>s.updateSettings); const addToast=useUIStore(s=>s.addToast); const qc=useQueryClient(); const mutation=useMutation({mutationFn:updateUserPreferences,onSuccess:()=>{void qc.invalidateQueries({queryKey:['user-preferences']}); addToast({type:'success',message:'Preferences saved'});}}); return <div className="page-container px-4 py-4 space-y-4"><Card className="flex items-center gap-4"><div className="h-14 w-14 rounded-full bg-tg-button flex items-center justify-center"><User className="h-7 w-7 text-tg-button-text"/></div><div><h1 className="text-lg font-bold text-tg-text">{user?.firstName} {user?.lastName}</h1><p className="text-sm text-tg-hint">@{user?.telegramUsername || 'No username'}</p></div></Card><Card className="space-y-3"><h2 className="font-semibold text-tg-text">Quick preferences</h2><div className="flex items-center justify-between"><span className="text-sm text-tg-text">Sound effects</span><Switch checked={settings.soundEnabled} onChange={(value)=>{update({soundEnabled:value});mutation.mutate({soundEnabled:value});}} label="Sound effects"/></div><div className="flex items-center justify-between"><span className="text-sm text-tg-text">Haptic feedback</span><Switch checked={settings.hapticEnabled} onChange={(value)=>{update({hapticEnabled:value});mutation.mutate({hapticEnabled:value});}} label="Haptic feedback"/></div><div className="flex items-center justify-between"><span className="text-sm text-tg-text">Theme</span><Select aria-label="Theme" value={settings.theme} onChange={(event)=>{const value=event.target.value; if(value==='system'||value==='light'||value==='dark'){update({theme:value});mutation.mutate({theme:value});}}}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></Select></div></Card><Card className="space-y-1">{sections.map(([id,label])=><button key={id} className="flex min-h-11 w-full items-center gap-3 rounded-xl px-2 text-left text-sm text-tg-text hover:bg-tg-section" onClick={()=>navigate(`/settings/${id}`)}><span className="flex-1">{label}</span><ChevronRight className="h-4 w-4 text-tg-hint"/></button>)}</Card><AutoBetConfig/>{isOperator&&<Card><Button variant="secondary" className="w-full" onClick={()=>navigate('/control')}><Shield className="mr-2 h-4 w-4"/>Control Panel</Button><Button variant="secondary" className="mt-2 w-full" onClick={()=>navigate('/analytics')}><BarChart3 className="mr-2 h-4 w-4"/>Analytics</Button>{isAdmin&&<Button className="mt-2 w-full" onClick={()=>navigate('/admin')}>Admin</Button>}</Card>}<Button variant="destructive" className="w-full" onClick={()=>{void logout();navigate('/onboarding');}}>Log out</Button></div>; }
