import { useState, useEffect } from 'react';
import { useGameStore } from '@/stores/gameStore';
import { useSettingsStore } from '@/stores/settingsStore';
import { useBet } from '@/hooks/betting/useBet';
import { useBalance } from '@/hooks/useBalance';
import { useHaptic } from '@/hooks/useHaptic';
import { isValidBetAmount, isValidAutoCashout, sanitizeNumberInput } from '@/utils/validation';
import { formatCurrency } from '@/utils/formatting';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { BetConfirmationSheet } from './BetConfirmationSheet';
import { BetPendingState } from './BetPendingState';
import { InsufficientBalanceDialog } from './InsufficientBalanceDialog';
export function BetPanel({ index = 0, amountOverride, onAmountChange }: { index?: 0 | 1; amountOverride?: string; onAmountChange?: (value: string) => void }) { const {config,phase,isPlacingBet}=useGameStore(); const {defaultBetAmount,defaultAutoCashout}=useSettingsStore(); const {place}=useBet(index); const {balance,currencySymbol}=useBalance(); const {impact}=useHaptic(); const [amount,setAmountState]=useState(String(defaultBetAmount)); const setAmount=(value:string)=>{setAmountState(value);onAmountChange?.(value);}; const [autoCashout,setAutoCashout]=useState(defaultAutoCashout?String(defaultAutoCashout):''); const [errors,setErrors]=useState<{amount?:string;autoCashout?:string}>({}); const [confirm,setConfirm]=useState(false); const [insufficient,setInsufficient]=useState(false); const min=config?.minBet??1,max=config?.maxBet??10000; useEffect(()=>{if(amountOverride!==undefined)setAmount(amountOverride);},[amountOverride]); const canBet=phase==='waiting'||phase==='countdown';
 const validate=()=>{const next:{amount?:string;autoCashout?:string}={};const a=isValidBetAmount(Number(amount),min,max);if(!a.valid)next.amount=a.error;if(autoCashout){const c=isValidAutoCashout(Number(autoCashout));if(!c.valid)next.autoCashout=c.error;}setErrors(next);return !Object.keys(next).length;};
 const submit=()=>{if(!validate()||!canBet||isPlacingBet)return;const numeric=Number(amount);if(numeric>(balance??0)){setInsufficient(true);return;}if(numeric>(balance??0)*0.5){setConfirm(true);return;}void doPlace();};
 const doPlace=async()=>{setConfirm(false);impact('medium');await place({amount:Number(amount),autoCashout:autoCashout?Number(autoCashout):null});};
 return <div className="card space-y-4">{isPlacingBet&&<BetPendingState/>}<div><label htmlFor="bet-amount" className="mb-2 block text-sm font-medium text-tg-text">Bet amount</label><Input id="bet-amount" inputMode="decimal" value={amount} onChange={(e)=>setAmount(sanitizeNumberInput(e.target.value))} aria-invalid={Boolean(errors.amount)} /><p className="mt-1 text-xs text-tg-hint">{currencySymbol}{formatCurrency(balance??0).replace(/^\$/, '')} available</p>{errors.amount&&<p className="text-xs text-crash-red">{errors.amount}</p>}</div><div><label htmlFor="auto-cashout" className="mb-2 block text-sm font-medium text-tg-text">Auto cashout (optional)</label><Input id="auto-cashout" inputMode="decimal" value={autoCashout} onChange={(e)=>setAutoCashout(sanitizeNumberInput(e.target.value))} aria-invalid={Boolean(errors.autoCashout)}/>{errors.autoCashout&&<p className="text-xs text-crash-red">{errors.autoCashout}</p>}</div><div className="flex gap-2 overflow-x-auto">{[1,5,10,25,50,100].map((preset)=><Button key={preset} size="sm" variant={Number(amount)===preset?'primary':'secondary'} onClick={()=>setAmount(String(preset))}>{currencySymbol}{preset}</Button>)}</div><Button className="w-full" loading={isPlacingBet} disabled={!canBet} onClick={submit}>Place bet</Button><BetConfirmationSheet open={confirm} amount={Number(amount)} onConfirm={()=>void doPlace()} onCancel={()=>setConfirm(false)}/><InsufficientBalanceDialog open={insufficient} onClose={()=>setInsufficient(false)}/></div>; }
